"""cria schema inicial

Revision ID: a9d8399d49e5
Revises:
Create Date: 2026-09-11 16:17:14.940796+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a9d8399d49e5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("sigla", sa.String(), nullable=True),
        sa.Column("ativa", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nome"),
    )
    op.create_table(
        "tecnologias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("categoria", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nome"),
    )
    op.create_table(
        "colaboradores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("area_id", sa.Integer(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("senha_hash", sa.String(), nullable=False),
        sa.Column("papel", sa.String(), nullable=False),
        sa.Column("colaborador_id", sa.Integer(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("ultimo_login", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["colaborador_id"],
            ["colaboradores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_usuarios_email"), ["email"], unique=True)

    op.create_table(
        "chamados",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("prioridade", sa.String(), nullable=False),
        sa.Column("area_id", sa.Integer(), nullable=True),
        sa.Column("solicitante_id", sa.Integer(), nullable=False),
        sa.Column("agente_id", sa.Integer(), nullable=True),
        sa.Column(
            "criado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("resolvido_em", sa.DateTime(), nullable=True),
        sa.Column("min_ate_resposta", sa.Integer(), nullable=True),
        sa.Column("min_ate_resolucao", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agente_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["solicitante_id"],
            ["colaboradores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chamados", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chamados_criado_em"), ["criado_em"], unique=False)
        batch_op.create_index(batch_op.f("ix_chamados_status"), ["status"], unique=False)

    op.create_table(
        "treinamentos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(), nullable=False),
        sa.Column("data_realizacao", sa.Date(), nullable=False),
        sa.Column("carga_horaria_h", sa.Float(), nullable=False),
        sa.Column("instrutor_id", sa.Integer(), nullable=False),
        sa.Column("area_id", sa.Integer(), nullable=True),
        sa.Column("formato", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrutor_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("treinamentos", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_treinamentos_data_realizacao"), ["data_realizacao"], unique=False
        )

    op.create_table(
        "materiais",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("url_arquivo", sa.String(), nullable=False),
        sa.Column("tecnologia_id", sa.Integer(), nullable=True),
        sa.Column("treinamento_id", sa.Integer(), nullable=True),
        sa.Column("autor_id", sa.Integer(), nullable=False),
        sa.Column(
            "publicado_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["autor_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tecnologia_id"],
            ["tecnologias.id"],
        ),
        sa.ForeignKeyConstraint(
            ["treinamento_id"],
            ["treinamentos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("materiais", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_materiais_publicado_em"), ["publicado_em"], unique=False
        )

    op.create_table(
        "mudancas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("area_id", sa.Integer(), nullable=True),
        sa.Column("chamado_id", sa.Integer(), nullable=True),
        sa.Column("responsavel_id", sa.Integer(), nullable=False),
        sa.Column(
            "solicitada_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("implantada_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["chamado_id"],
            ["chamados.id"],
        ),
        sa.ForeignKeyConstraint(
            ["responsavel_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mudancas", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mudancas_implantada_em"), ["implantada_em"], unique=False
        )

    op.create_table(
        "participantes",
        sa.Column("treinamento_id", sa.Integer(), nullable=False),
        sa.Column("colaborador_id", sa.Integer(), nullable=False),
        sa.Column("presente", sa.Boolean(), nullable=False),
        sa.Column("nota_reacao", sa.Integer(), nullable=True),
        sa.Column("nota_pre", sa.Integer(), nullable=True),
        sa.Column("nota_pos", sa.Integer(), nullable=True),
        sa.CheckConstraint("nota_pos  BETWEEN 0 AND 100"),
        sa.CheckConstraint("nota_pre  BETWEEN 0 AND 100"),
        sa.CheckConstraint("nota_reacao BETWEEN 1 AND 5"),
        sa.ForeignKeyConstraint(
            ["colaborador_id"],
            ["colaboradores.id"],
        ),
        sa.ForeignKeyConstraint(["treinamento_id"], ["treinamentos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("treinamento_id", "colaborador_id"),
    )
    op.create_table(
        "treinamento_tecnologias",
        sa.Column("treinamento_id", sa.Integer(), nullable=False),
        sa.Column("tecnologia_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tecnologia_id"],
            ["tecnologias.id"],
        ),
        sa.ForeignKeyConstraint(["treinamento_id"], ["treinamentos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("treinamento_id", "tecnologia_id"),
    )
    op.create_table(
        "comunicacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(), nullable=False),
        sa.Column("canal", sa.String(), nullable=False),
        sa.Column("area_id", sa.Integer(), nullable=True),
        sa.Column("material_id", sa.Integer(), nullable=True),
        sa.Column("autor_id", sa.Integer(), nullable=False),
        sa.Column(
            "enviada_em",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["autor_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materiais.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("comunicacoes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_comunicacoes_enviada_em"), ["enviada_em"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comunicacoes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comunicacoes_enviada_em"))

    op.drop_table("comunicacoes")
    op.drop_table("treinamento_tecnologias")
    op.drop_table("participantes")
    with op.batch_alter_table("mudancas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mudancas_implantada_em"))

    op.drop_table("mudancas")
    with op.batch_alter_table("materiais", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_materiais_publicado_em"))

    op.drop_table("materiais")
    with op.batch_alter_table("treinamentos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_treinamentos_data_realizacao"))

    op.drop_table("treinamentos")
    with op.batch_alter_table("chamados", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chamados_status"))
        batch_op.drop_index(batch_op.f("ix_chamados_criado_em"))

    op.drop_table("chamados")
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usuarios_email"))

    op.drop_table("usuarios")
    op.drop_table("colaboradores")
    op.drop_table("tecnologias")
    op.drop_table("areas")
    # ### end Alembic commands ###
